nome = "ído"
description = "Um tema de blog clássico"
licença = "MIT"
homepage = "https://github.com/getzola/hyde"
min_version = "0.11.0"
demo = "https://zola-hyde.netlify.com"

[extra]
hyde_sticky = verdadeiro
hyde_reverse = falso
hyde_theme = ""
hyde_links = [
]

[autor]
nome = "Vincent Prouillet"
homepage = "https://www.vincentprouillet.com"

[Original]
autor = "mdo"
homepage = "http://markdotto.com/"
repo = "https://www.github.com/mdo/hyde"
